name: 📣 Notify Telegram

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, closed]
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: 📩 Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          format: html
          parse_mode: HTML
          message: >
            <b><u>${{ github.event.head_commit.message }}</u></b>
            &#10;🔸 <b>Repo/Branch:</b> <code>${{ github.repository }}/${{ github.ref_name }}</code>
            &#10;🔸 <b>Author:</b> <code>${{ github.event.head_commit.author.name }}</code>
            &#10;🔸 <b>Commit:</b> <a href="https://github.com/${{ github.repository }}/commit/${{ github.sha }}">View on GitHub</a>
