name: 📣 Notify Telegram

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, closed]
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            📢 **${{ github.event.head_commit.message }}**
            - Repo/Branch: ${{ github.repository }}/${{ github.ref_name }}
            - Author: ${{ github.event.head_commit.author.name }}
            - Commit ID: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

