name: 📣 Notify Telegram

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, closed]
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            📢 *GitHub Event Notification*
            🔸 *Event:* ${{ github.event_name }}
            🔸 *Repo:* ${{ github.repository }}
            🔸 *User:* ${{ github.actor }}
